version: "3.1"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - api/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - app/.env
    ports:
      - "3001:3001"
    depends_on:
      - api
  db:
    image: postgres:latest
    container_name: database
    env_file:
      - api/.env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  data:
    name: api_data
